/* nsIMyPortalColorStyleSheet.idl
 * Copyright (C) 2005-2007 Max Smolens
 *
 * This file is part of My Portal.
 *
 * My Portal is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation; either version 2 of the License,
 * or (at your option) any later version.
 *
 * My Portal is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with My Portal; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA
 */

#include "nsISupports.idl"

interface nsIDOMCSSStyleSheet;

[scriptable, uuid(4d5935de-ca00-4398-83da-09e4ca9cf210)]
interface nsIMyPortalColorStyleSheet : nsISupports
{
        /**
         * Set the style sheet on which to operate.
         *
         * @param styleSheet the style sheet
         *
         * @note should be called immediately after construction
         */
        void setStyleSheet(in nsIDOMCSSStyleSheet styleSheet);

        /**
         * Update colors from preferences.
         */
        void update();

        /**
         * Unload.
         */
        void unload();
};
